name: CI

on: [schedule]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Delete it/* branches
      uses: dawidd6/action-delete-branch@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branches: '*'
        prefix: 'it/'
