name: Go

on: [push]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13.x'
    - name: checkout
      uses: actions/checkout@v2
      #
    - name: setup-coverage
      run: |
        curl -L --output code-climate https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
        chmod +x ./code-climate
        ./code-climate before-build
    - name: unit-test
      run: go test ./... -coverprofile cover.out 
    - name: report-coverage
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_REPORTER_ID }}
      run: |
        ./code-climate format-coverage cover.out --input-type gocov --prefix github.com/SAP/jenkins-library/
        ./code-climate upload-coverage
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13.x'
    - name: checkout
      uses: actions/checkout@v2
    - name: format
      run: go fmt ./...
    - name: verify
      run: git diff --name-only --exit-code
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13.x'
    - name: checkout
      uses: actions/checkout@v2
    - name: generate
      run: go run pkg/generator/step-metadata.go
    - name: verify
      run: git diff --name-only --exit-code
  dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13.x'
    - name: checkout
      uses: actions/checkout@v2
    - name: cleanup dependencies
      run: go mod tidy
    - name: verify
      run: git diff --name-only --exit-code
