name: Groovy

on: [push]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: checkout
      uses: actions/checkout@v2
    - name: unit-test
      uses: paambaati/codeclimate-action@v2.4.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CODE_CLIMATE_REPORTER_ID}}
        JACOCO_SOURCE_PATH: "src vars test"
      with:
        coverageCommand: |
          mvn --batch-mode clean verify -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          && ./cc-reporter format-coverage target/site/jacoco/jacoco.xml --input-type jacoco
